name: Build and deploy to production domain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "12.x"
    - run: npm ci
    - run: npm run build --if-present
      env:
        VUE_APP_OPENCAGEDATA_API_KEY: ${{ secrets.VUE_APP_OPENCAGEDATA_API_KEY }}
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.TTI0_NET_SFTP_SERVER }}
        port: 22
        username: ${{ secrets.TTI0_NET_SFTP_USER }}
        password: ${{ secrets.TTI0_NET_SFTP_PASSWORD }}
        localDir: 'dist'
        remoteDir: '/'
